version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: |
          echo "Circle branch is ${CIRCLE_BRANCH}"
          echo $PWD
          ls -l
          node --version
          yarn --version
      # - restore_cache:
      #     keys:
      #       - yarn-deps-{{ checksum "yarn.lock" }}
      #       - yarn-deps
      - run:
          name: Install node_modules
          command: |
            yarn install
            ls -l
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: yarn-deps-{{ checksum "yarn.lock" }}-{{ epoch }}
      - run:
          name: Package vsix
          command: |
            echo $PWD
            ls -l
            npx vsce package
      - run:
          name: Copy vsix
          command: |
            mkdir artifacts
            cp *.vsix artifacts/
      - store_artifacts:
            path: yarn.lock
      - persist_to_workspace:
            root: .
            paths:
                - .

      # Save the artifacts
      - store_artifacts:
          path: artifacts/

workflows:
  build-test:
    jobs:
      - build
      