# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: label

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: yarn --version

      # Install node modules and create a vsix file
      - name: Run a multi-line script
        run: |
          yarn
          npx vsce package
