# This is a basic workflow to help you get started with Actions

name: Old-CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: yarn --version

      # Install node modules and create a vsix file
      - name: Run a multi-line script
        run: |
          yarn
          npx vsce package
      - name: Archive an artifact
        uses: actions/upload-artifact@v2
        with:
          name: vsix_file
          path: ./*.vsix
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: vsix_file

